print('Welcome to ProgramSurvey. This is currently under development. Click the square, so you can fully see.')
print('Hello world!')
print('Enter a code(to secure your data, and to change your info.)')
code = input()  
print('Remember that code, ok?')     
print('What is your name?')   
print('Type your name.')
myName = input()
print('The length of your name is:')
print(len(myName))
print('What is your age?')   
myAge = input()
print('You will be ' + str(int(myAge) + 1) + ' in a year/few months!')
print('It is nice to meet you!')
print('What do you like to do, ' + myName + '?')
print('Type what you like doing.') 
hobby = input()
print(':O You do that in your free time as well?')
print('' + myName + ': Yeah, Like we are clones, or something!')
print('' + myName + ', the program has now ended. You may now exit.')
print('This will be a full personal info security system in the future, so there will be a code thingy sometime.')
print('I will make announcements on my GitHub page. https://github.com/SakuraThePythonProgrammer   See you later!')



